spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_analysis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.mysql.cj.jdbc.MysqlDataSource
    username: root
    password: z960518
  data:
    neo4j:
      uri: bolt://47.95.11.44:7787
      username: neo4j
      password: movie@159357

mybatis:
  config-location: classpath:/mybatis-config.xml

server:
  port: 8088

dataScienceServer: "http://127.0.0.1:5000"

