spring:
  datasource:
    url: jdbc:mysql://10.103.244.129:3306/movie_data_analysis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.mysql.cj.jdbc.MysqlDataSource
    username: root
    password: yang1290

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml