spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/movie_analysis_v5?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://39.107.61.165:3306/movie_analysis_v5?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.mysql.cj.jdbc.MysqlDataSource
    username: root
#    password: 199829
    password: movie123.
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456

mybatis:
  config-location: classpath:/mybatis-config.xml

server:
  port: 8008

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dataScienceServer: "http://106.54.68.249:10012"

