spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_analysis_v4?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.mysql.cj.jdbc.MysqlDataSource
    username: root
    password: movie123.
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: movie123.

mybatis:
  config-location: classpath:/mybatis-config.xml

server:
  port: 10020

dataScienceServer: "http://106.54.68.249:10012"