spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_analysis_v5?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://106.54.68.249:3326/movie_analysis_v4?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.mysql.cj.jdbc.MysqlDataSource
    username: root
    password: z960518
#    password: movie@159357
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456

mybatis:
  config-location: classpath:/mybatis-config.xml

server:
  port: 8008

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dataScienceServer: "http://106.54.68.249:10012"

