package com.xzx.mapper;

import com.xzx.entity.Actor;
import com.xzx.entity.ActorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    long countByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int deleteByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int insert(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int insertSelective(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    List<Actor> selectByExampleWithRowbounds(ActorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    List<Actor> selectByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    Actor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") Actor record, @Param("example") ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByExample(@Param("record") Actor record, @Param("example") ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByPrimaryKeySelective(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByPrimaryKey(Actor record);
}