package com.xzx.mapper;

import com.xzx.entity.Director;
import com.xzx.entity.DirectorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DirectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    long countByExample(DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int deleteByExample(DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int insert(Director record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int insertSelective(Director record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    List<Director> selectByExampleWithRowbounds(DirectorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    List<Director> selectByExample(DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    Director selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") Director record, @Param("example") DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByExample(@Param("record") Director record, @Param("example") DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByPrimaryKeySelective(Director record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByPrimaryKey(Director record);
}