package com.xzx.mapper;

import com.xzx.entity.Movie;
import com.xzx.entity.MovieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    long countByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    int deleteByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    int insertSelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    List<Movie> selectByExampleWithRowbounds(MovieExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    List<Movie> selectByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    Movie selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    int updateByExample(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    int updateByPrimaryKeySelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    int updateByPrimaryKey(Movie record);
}