package com.xzx.mapper;

import com.xzx.entity.Scenarist;
import com.xzx.entity.ScenaristExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ScenaristMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    long countByExample(ScenaristExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int deleteByExample(ScenaristExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int insert(Scenarist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int insertSelective(Scenarist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    List<Scenarist> selectByExampleWithRowbounds(ScenaristExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    List<Scenarist> selectByExample(ScenaristExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    Scenarist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") Scenarist record, @Param("example") ScenaristExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByExample(@Param("record") Scenarist record, @Param("example") ScenaristExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByPrimaryKeySelective(Scenarist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenarist_table
     *
     * @mbg.generated Fri Dec 13 18:45:29 CST 2019
     */
    int updateByPrimaryKey(Scenarist record);
}