package com.xzx.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MovieExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public MovieExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeIsNull() {
            addCriterion("release_time is null");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeIsNotNull() {
            addCriterion("release_time is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeEqualTo(Date value) {
            addCriterionForJDBCDate("release_time =", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("release_time <>", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("release_time >", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("release_time >=", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeLessThan(Date value) {
            addCriterionForJDBCDate("release_time <", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("release_time <=", value, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeIn(List<Date> values) {
            addCriterionForJDBCDate("release_time in", values, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("release_time not in", values, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("release_time between", value1, value2, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("release_time not between", value1, value2, "releaseTime");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaIsNull() {
            addCriterion("release_area is null");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaIsNotNull() {
            addCriterion("release_area is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaEqualTo(String value) {
            addCriterion("release_area =", value, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaNotEqualTo(String value) {
            addCriterion("release_area <>", value, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaGreaterThan(String value) {
            addCriterion("release_area >", value, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaGreaterThanOrEqualTo(String value) {
            addCriterion("release_area >=", value, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaLessThan(String value) {
            addCriterion("release_area <", value, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaLessThanOrEqualTo(String value) {
            addCriterion("release_area <=", value, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaLike(String value) {
            addCriterion("release_area like", value, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaNotLike(String value) {
            addCriterion("release_area not like", value, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaIn(List<String> values) {
            addCriterion("release_area in", values, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaNotIn(List<String> values) {
            addCriterion("release_area not in", values, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaBetween(String value1, String value2) {
            addCriterion("release_area between", value1, value2, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andReleaseAreaNotBetween(String value1, String value2) {
            addCriterion("release_area not between", value1, value2, "releaseArea");
            return (Criteria) this;
        }

        public Criteria andTechnologyIsNull() {
            addCriterion("technology is null");
            return (Criteria) this;
        }

        public Criteria andTechnologyIsNotNull() {
            addCriterion("technology is not null");
            return (Criteria) this;
        }

        public Criteria andTechnologyEqualTo(String value) {
            addCriterion("technology =", value, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyNotEqualTo(String value) {
            addCriterion("technology <>", value, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyGreaterThan(String value) {
            addCriterion("technology >", value, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyGreaterThanOrEqualTo(String value) {
            addCriterion("technology >=", value, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyLessThan(String value) {
            addCriterion("technology <", value, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyLessThanOrEqualTo(String value) {
            addCriterion("technology <=", value, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyLike(String value) {
            addCriterion("technology like", value, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyNotLike(String value) {
            addCriterion("technology not like", value, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyIn(List<String> values) {
            addCriterion("technology in", values, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyNotIn(List<String> values) {
            addCriterion("technology not in", values, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyBetween(String value1, String value2) {
            addCriterion("technology between", value1, value2, "technology");
            return (Criteria) this;
        }

        public Criteria andTechnologyNotBetween(String value1, String value2) {
            addCriterion("technology not between", value1, value2, "technology");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIsNull() {
            addCriterion("second_type is null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIsNotNull() {
            addCriterion("second_type is not null");
            return (Criteria) this;
        }

        public Criteria andSecondTypeEqualTo(String value) {
            addCriterion("second_type =", value, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNotEqualTo(String value) {
            addCriterion("second_type <>", value, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeGreaterThan(String value) {
            addCriterion("second_type >", value, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeGreaterThanOrEqualTo(String value) {
            addCriterion("second_type >=", value, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeLessThan(String value) {
            addCriterion("second_type <", value, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeLessThanOrEqualTo(String value) {
            addCriterion("second_type <=", value, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeLike(String value) {
            addCriterion("second_type like", value, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNotLike(String value) {
            addCriterion("second_type not like", value, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeIn(List<String> values) {
            addCriterion("second_type in", values, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNotIn(List<String> values) {
            addCriterion("second_type not in", values, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeBetween(String value1, String value2) {
            addCriterion("second_type between", value1, value2, "secondType");
            return (Criteria) this;
        }

        public Criteria andSecondTypeNotBetween(String value1, String value2) {
            addCriterion("second_type not between", value1, value2, "secondType");
            return (Criteria) this;
        }

        public Criteria andBoxofficeIsNull() {
            addCriterion("boxoffice is null");
            return (Criteria) this;
        }

        public Criteria andBoxofficeIsNotNull() {
            addCriterion("boxoffice is not null");
            return (Criteria) this;
        }

        public Criteria andBoxofficeEqualTo(Float value) {
            addCriterion("boxoffice =", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeNotEqualTo(Float value) {
            addCriterion("boxoffice <>", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeGreaterThan(Float value) {
            addCriterion("boxoffice >", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeGreaterThanOrEqualTo(Float value) {
            addCriterion("boxoffice >=", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeLessThan(Float value) {
            addCriterion("boxoffice <", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeLessThanOrEqualTo(Float value) {
            addCriterion("boxoffice <=", value, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeIn(List<Float> values) {
            addCriterion("boxoffice in", values, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeNotIn(List<Float> values) {
            addCriterion("boxoffice not in", values, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeBetween(Float value1, Float value2) {
            addCriterion("boxoffice between", value1, value2, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andBoxofficeNotBetween(Float value1, Float value2) {
            addCriterion("boxoffice not between", value1, value2, "boxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeIsNull() {
            addCriterion("first_boxoffice is null");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeIsNotNull() {
            addCriterion("first_boxoffice is not null");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeEqualTo(Float value) {
            addCriterion("first_boxoffice =", value, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeNotEqualTo(Float value) {
            addCriterion("first_boxoffice <>", value, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeGreaterThan(Float value) {
            addCriterion("first_boxoffice >", value, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeGreaterThanOrEqualTo(Float value) {
            addCriterion("first_boxoffice >=", value, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeLessThan(Float value) {
            addCriterion("first_boxoffice <", value, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeLessThanOrEqualTo(Float value) {
            addCriterion("first_boxoffice <=", value, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeIn(List<Float> values) {
            addCriterion("first_boxoffice in", values, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeNotIn(List<Float> values) {
            addCriterion("first_boxoffice not in", values, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeBetween(Float value1, Float value2) {
            addCriterion("first_boxoffice between", value1, value2, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andFirstBoxofficeNotBetween(Float value1, Float value2) {
            addCriterion("first_boxoffice not between", value1, value2, "firstBoxoffice");
            return (Criteria) this;
        }

        public Criteria andActorIsNull() {
            addCriterion("actor is null");
            return (Criteria) this;
        }

        public Criteria andActorIsNotNull() {
            addCriterion("actor is not null");
            return (Criteria) this;
        }

        public Criteria andActorEqualTo(String value) {
            addCriterion("actor =", value, "actor");
            return (Criteria) this;
        }

        public Criteria andActorNotEqualTo(String value) {
            addCriterion("actor <>", value, "actor");
            return (Criteria) this;
        }

        public Criteria andActorGreaterThan(String value) {
            addCriterion("actor >", value, "actor");
            return (Criteria) this;
        }

        public Criteria andActorGreaterThanOrEqualTo(String value) {
            addCriterion("actor >=", value, "actor");
            return (Criteria) this;
        }

        public Criteria andActorLessThan(String value) {
            addCriterion("actor <", value, "actor");
            return (Criteria) this;
        }

        public Criteria andActorLessThanOrEqualTo(String value) {
            addCriterion("actor <=", value, "actor");
            return (Criteria) this;
        }

        public Criteria andActorLike(String value) {
            addCriterion("actor like", value, "actor");
            return (Criteria) this;
        }

        public Criteria andActorNotLike(String value) {
            addCriterion("actor not like", value, "actor");
            return (Criteria) this;
        }

        public Criteria andActorIn(List<String> values) {
            addCriterion("actor in", values, "actor");
            return (Criteria) this;
        }

        public Criteria andActorNotIn(List<String> values) {
            addCriterion("actor not in", values, "actor");
            return (Criteria) this;
        }

        public Criteria andActorBetween(String value1, String value2) {
            addCriterion("actor between", value1, value2, "actor");
            return (Criteria) this;
        }

        public Criteria andActorNotBetween(String value1, String value2) {
            addCriterion("actor not between", value1, value2, "actor");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyIsNull() {
            addCriterion("issue_company is null");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyIsNotNull() {
            addCriterion("issue_company is not null");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyEqualTo(String value) {
            addCriterion("issue_company =", value, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyNotEqualTo(String value) {
            addCriterion("issue_company <>", value, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyGreaterThan(String value) {
            addCriterion("issue_company >", value, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("issue_company >=", value, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyLessThan(String value) {
            addCriterion("issue_company <", value, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyLessThanOrEqualTo(String value) {
            addCriterion("issue_company <=", value, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyLike(String value) {
            addCriterion("issue_company like", value, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyNotLike(String value) {
            addCriterion("issue_company not like", value, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyIn(List<String> values) {
            addCriterion("issue_company in", values, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyNotIn(List<String> values) {
            addCriterion("issue_company not in", values, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyBetween(String value1, String value2) {
            addCriterion("issue_company between", value1, value2, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andIssueCompanyNotBetween(String value1, String value2) {
            addCriterion("issue_company not between", value1, value2, "issueCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyIsNull() {
            addCriterion("manu_company is null");
            return (Criteria) this;
        }

        public Criteria andManuCompanyIsNotNull() {
            addCriterion("manu_company is not null");
            return (Criteria) this;
        }

        public Criteria andManuCompanyEqualTo(String value) {
            addCriterion("manu_company =", value, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyNotEqualTo(String value) {
            addCriterion("manu_company <>", value, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyGreaterThan(String value) {
            addCriterion("manu_company >", value, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("manu_company >=", value, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyLessThan(String value) {
            addCriterion("manu_company <", value, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyLessThanOrEqualTo(String value) {
            addCriterion("manu_company <=", value, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyLike(String value) {
            addCriterion("manu_company like", value, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyNotLike(String value) {
            addCriterion("manu_company not like", value, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyIn(List<String> values) {
            addCriterion("manu_company in", values, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyNotIn(List<String> values) {
            addCriterion("manu_company not in", values, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyBetween(String value1, String value2) {
            addCriterion("manu_company between", value1, value2, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andManuCompanyNotBetween(String value1, String value2) {
            addCriterion("manu_company not between", value1, value2, "manuCompany");
            return (Criteria) this;
        }

        public Criteria andIsIpIsNull() {
            addCriterion("is_ip is null");
            return (Criteria) this;
        }

        public Criteria andIsIpIsNotNull() {
            addCriterion("is_ip is not null");
            return (Criteria) this;
        }

        public Criteria andIsIpEqualTo(Boolean value) {
            addCriterion("is_ip =", value, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpNotEqualTo(Boolean value) {
            addCriterion("is_ip <>", value, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpGreaterThan(Boolean value) {
            addCriterion("is_ip >", value, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_ip >=", value, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpLessThan(Boolean value) {
            addCriterion("is_ip <", value, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpLessThanOrEqualTo(Boolean value) {
            addCriterion("is_ip <=", value, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpIn(List<Boolean> values) {
            addCriterion("is_ip in", values, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpNotIn(List<Boolean> values) {
            addCriterion("is_ip not in", values, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpBetween(Boolean value1, Boolean value2) {
            addCriterion("is_ip between", value1, value2, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsIpNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_ip not between", value1, value2, "isIp");
            return (Criteria) this;
        }

        public Criteria andIsSequelIsNull() {
            addCriterion("is_sequel is null");
            return (Criteria) this;
        }

        public Criteria andIsSequelIsNotNull() {
            addCriterion("is_sequel is not null");
            return (Criteria) this;
        }

        public Criteria andIsSequelEqualTo(Boolean value) {
            addCriterion("is_sequel =", value, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelNotEqualTo(Boolean value) {
            addCriterion("is_sequel <>", value, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelGreaterThan(Boolean value) {
            addCriterion("is_sequel >", value, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_sequel >=", value, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelLessThan(Boolean value) {
            addCriterion("is_sequel <", value, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelLessThanOrEqualTo(Boolean value) {
            addCriterion("is_sequel <=", value, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelIn(List<Boolean> values) {
            addCriterion("is_sequel in", values, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelNotIn(List<Boolean> values) {
            addCriterion("is_sequel not in", values, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sequel between", value1, value2, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsSequelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sequel not between", value1, value2, "isSequel");
            return (Criteria) this;
        }

        public Criteria andIsNetworkIsNull() {
            addCriterion("is_network is null");
            return (Criteria) this;
        }

        public Criteria andIsNetworkIsNotNull() {
            addCriterion("is_network is not null");
            return (Criteria) this;
        }

        public Criteria andIsNetworkEqualTo(Boolean value) {
            addCriterion("is_network =", value, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkNotEqualTo(Boolean value) {
            addCriterion("is_network <>", value, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkGreaterThan(Boolean value) {
            addCriterion("is_network >", value, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_network >=", value, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkLessThan(Boolean value) {
            addCriterion("is_network <", value, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkLessThanOrEqualTo(Boolean value) {
            addCriterion("is_network <=", value, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkIn(List<Boolean> values) {
            addCriterion("is_network in", values, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkNotIn(List<Boolean> values) {
            addCriterion("is_network not in", values, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkBetween(Boolean value1, Boolean value2) {
            addCriterion("is_network between", value1, value2, "isNetwork");
            return (Criteria) this;
        }

        public Criteria andIsNetworkNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_network not between", value1, value2, "isNetwork");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movie_table
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 11 17:11:59 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table movie_table
     *
     * @mbg.generated Wed Dec 11 17:11:59 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}