package com.xzx.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.id
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.username
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.password
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.role
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    private Boolean role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.status
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.register_time
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.login_time
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.id
     *
     * @return the value of user_table.id
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.id
     *
     * @param id the value for user_table.id
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.username
     *
     * @return the value of user_table.username
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.username
     *
     * @param username the value for user_table.username
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.password
     *
     * @return the value of user_table.password
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.password
     *
     * @param password the value for user_table.password
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.role
     *
     * @return the value of user_table.role
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public Boolean getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.role
     *
     * @param role the value for user_table.role
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public void setRole(Boolean role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.status
     *
     * @return the value of user_table.status
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.status
     *
     * @param status the value for user_table.status
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.register_time
     *
     * @return the value of user_table.register_time
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.register_time
     *
     * @param registerTime the value for user_table.register_time
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.login_time
     *
     * @return the value of user_table.login_time
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.login_time
     *
     * @param loginTime the value for user_table.login_time
     *
     * @mbg.generated Sun Feb 02 15:00:32 CST 2020
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}